version: "3.8"

services:
  parceiros-indicacao:
    image: ghcr.io/vctrin/parceiros-indicacao:latest
    environment:
      NODE_ENV: production
      PORT: 3000
    networks:
      - network_public
    deploy:
      replicas: 1
      update_config:
        order: start-first
        parallelism: 1
        failure_action: rollback
      rollback_config:
        order: stop-first
        parallelism: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.docker.network=network_public
        - traefik.http.routers.parceiros-indicacao.rule=Host(`parcerias.gluotech.com`)
        - traefik.http.routers.parceiros-indicacao.entrypoints=websecure
        - traefik.http.routers.parceiros-indicacao.tls=true
        - traefik.http.routers.parceiros-indicacao.tls.certresolver=letsencrypt
        - traefik.http.services.parceiros-indicacao.loadbalancer.server.port=3000

networks:
  network_public:
    external: true
